[openshift-3.11] Remove images/manila-provisioner
`doozer rpms:rebase-and-build` failed because of an error in an image:
```
ValueError: Image manila-provisioner has name_in_bundle=manila-provisioner, which is already taken by image openshift-manila-provisioner
```
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp3/565/console
Proposing to delete the `mode: disabled` image `images/manila-provisioner.yml`, as it has been `mode: wip` or `mode: disabled` since [November 2018](https://github.com/openshift/ocp-build-data/commit/c3fb572ba)