Pin rhsl-ruby-2.5 to previous version
`logging-fluentd` had this issue:
```
Error: Package: glibc-2.17-292.el7.i686 (rhel-server-rpms-x86_64)
 Requires: glibc-common = 2.17-292.el7
 Installed: glibc-common-2.17-307.el7.1.x86_64 (@anaconda/7.8)
```
Current `:latest` of `rhscl-ruby-25-rhel7` includes a pre-release glibc,
which causes this. This patch is intended to be temporary.