[ART-788] Update sources of images/template-service-broker.yml
This image didn't have a previous github source.

The validation looks fine:
```
$ validate-ocp-build-data images/template-service-broker.yml
Validating images/template-service-broker.yml

$ echo $?
0
```

But I imagine it will fail with:
```
BuildError: package (container) template-service-broker-container not in list for tag rhaos-4.2-rhel-7-candidate
```

Because when I try to search for it I get nothing:
```
$ brew list-pkgs --tag rhaos-4.2-rhel-7 --package template-service-broker-container
(no matching packages)
```