Revert 4 images to rhel8
[monitoring-plugin](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235742)
```
ENV NGINX_VERSION=1.20
RUN yum -y module enable nginx:$NGINX_VERSION  &&     INSTALL_PKGS="nginx"  &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS
Error: Problems in request:
missing groups or modules: nginx:1.20
```

[azure-workload-identity-webook](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235741)
```
BuildError: package (container) ose-azure-workload-identity-webhook-container not in list for tag rhaos-4.15-rhel-9-candidate
```

[ose-cluster-olm-operator](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235731)
```
BuildError: package (container) ose-cluster-olm-operator-container not in list for tag rhaos-4.15-rhel-9-candidate
```
[ose-libvirt-machine-controllers](https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=57235728)
```
RUN yum install -y libvirt-devel
No match for argument: libvirt-devel
```