MTC: update dnf module to match builder image
Caused after updating  nodejs-16 images to nodejs-20
https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/art-mtc-tenant/applications/mtc-1-8/pipelineruns/mtc-1-8-openshift-migration-ui-tt7fh/logs?task=build-images
```
The operation would result in switching of module 'nodejs' stream '20'
  to stream '16'
Error: It is not possible to switch enabled streams of a module unless
  explicitly enabled via configuration option module_stream_switch.
It is recommended to rather remove all installed content from the
  module, and reset the module using 'dnf module reset <module_name>'
  command. After you reset the module, you can install the other stream.
```